# Generated by Django 2.1.7 on 2019-02-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Bairro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Cidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('logo_tipo', models.ImageField(blank=True, null=True, upload_to='config/images', verbose_name='Logo tipo')),
                ('telefone', models.EmailField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('celular', models.EmailField(blank=True, max_length=16, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=40, null=True, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('titulo', models.CharField(blank=True, max_length=60, null=True, verbose_name='Título')),
                ('image', models.ImageField(blank=True, null=True, upload_to='config/images', verbose_name='Imagem 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='config/images', verbose_name='Imagem 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='config/images', verbose_name='Imagem 3')),
                ('sobre', models.TextField(blank=True, null=True, verbose_name='Sobre nós')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='Finalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Finalidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
            options={
                'verbose_name': 'Finalidade',
                'verbose_name_plural': 'Finalidades',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imovel/images', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('descricao_resumida', models.TextField(blank=True, max_length=80, null=True, verbose_name='Decrição resumida')),
                ('valor', models.CharField(blank=True, max_length=60, null=True, verbose_name='Valor')),
                ('quarto', models.IntegerField(default=0, verbose_name='Quarto')),
                ('bainheiro', models.IntegerField(default=0, verbose_name='Bainheiro')),
                ('vaga', models.IntegerField(default=0, verbose_name='Vaga')),
                ('area', models.FloatField(default=0, verbose_name='Area')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imobiliaria.Bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imobiliaria.Cidade')),
                ('finalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imobiliaria.Finalidade')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80, unique=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
            },
        ),
        migrations.AddField(
            model_name='imovel',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imobiliaria.Status'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imobiliaria.Tipo'),
        ),
        migrations.AddField(
            model_name='imagem',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='imobiliaria.Imovel'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imobiliaria.Cidade'),
        ),
    ]
